[package]
name = "avant-rbx/avant-plugin"
repository = "https://github.com/Avant-Rbx/Avant-Plugin"
description = "Roblox Studio plugin for running unit tests."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "1.0.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
AvantRuntime = "avant-rbx/avant-runtime@1.2.3"
NexusPluginComponents = "thenexusavenger/nexus-plugin-components@1.2.0"